# Default to "jdbc:postgresql://example.com:5432/database" so that the application at least starts up when
# JDBC_DATABASE_URL is not set. We use this here to reduce friction when newcomers work with this getting started
# application. Production applications should not have a default like this, especially not ones that have credentials
# in them!

server.port: ${PORT:5000}
spring.datasource.url: ${DATABASE_URL}
hibernate.connection.url: ${DATABASE_URL}

spring.datasource.username: caiodonat
spring.datasource.password: 12qwaszx
spring.datasource.driver-class-name: org.postgresql.Driver
# spring.jpa.database-platform :  org.hibernate.dialect.MySQL5Dialect
spring.jpa.generate-ddl: true
spring.jpa.hibernate.ddl-auto:  update

# SWAGGER
springdoc.swagger-ui.path: /v1/docs
springdoc.api-docs.path: /v1/docs-api
springdoc.swagger-ui.tryItOutEnabled: true
springdoc.swagger-ui.filter: true
openapi.dev-url: http://localhost:${PORT:5000}
openapi.prod-url: ${APP_URL} 
