name: Deploy
on:
  workflow_run:
    workflows: [Merge main]
    types:
      - completed
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉"
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.13 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "api-farmacia-higia-java" #Must be unique in Heroku
          heroku_email: "caiohdonat@gmail.com"